from setuptools import setup, find_packages

setup(
    name='apparate',
    version='0.1',
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        "asn1crypto==0.24.0",
        "attrs==18.1.0",
        "Automat==0.6.0",
        "beautifulsoup4==4.6.0",
        "cffi==1.11.5",
        "click==6.7",
        "constantly==15.1.0",
        "cryptography==2.2.2",
        "cssselect==1.0.3",
        "gitdb2==2.0.3",
        "GitPython==2.1.9",
        "hyperlink==18.0.0",
        "idna==2.6",
        "incremental==17.5.0",
        "lxml==4.2.1",
        "parsel==1.4.0",
        "pyasn1==0.4.2",
        "pyasn1-modules==0.2.1",
        "pycparser==2.18",
        "PyDispatcher==2.0.5",
        "PyGithub==1.39",
        "PyJWT==1.6.1",
        "pyOpenSSL==17.5.0",
        "queuelib==1.5.0",
        "Scrapy==1.5.0",
        "selenium==3.12.0",
        "service-identity==17.0.0",
        "six==1.11.0",
        "smmap2==2.0.3",
        "Twisted==18.4.0",
        "w3lib==1.19.0",
        "zope.interface==4.5.0"
    ],
    entry_points='''
        [console_scripts]
        apparate=scripts.apparate:apparate
    ''',
)
